language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-cengage' ]; then cd .. && eval "mv $currentfolder generator-cengage" && cd generator-cengage; fi

